name: php-ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2']

      services:
        postgres:
          image: postgres:latest
          env:
            POSTGRES_USER: hexlet_test
            POSTGRES_PASSWORD: hexlet_test
            POSTGRES_DB: hexlet_test
          ports:
            - 5432/tcp

    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: install
        run: make install

      - name: lint
        run: make lint

      - name: tests
        run: make test

      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true
